name: Publish to NPM

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Publish to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish --access public

      - name: Cleanup
        if: always()
        run: rm .npmrc || true
