name: Create Release

on:
  push:
    tags:
      - "**"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
